REGISTRATION_PAGE_URL = "https://stellarburgers.nomoreparties.site/register"
LOGIN_PAGE_URL = "https://stellarburgers.nomoreparties.site/login"
MAIN_PAGE_URL = "https://stellarburgers.nomoreparties.site"
PROFILE_PAGE_URL = "https://stellarburgers.nomoreparties.site/account/profile"
RESET_PASSWORD_PAGE_URL = "https://stellarburgers.nomoreparties.site/forgot-password"
